#Preferences
#Sun Jul 19 15:55:53 GMT+03:00 2026
action_bar=true
etf_button=true
folder_pack=true
options=true
original_screen=true
polytone_button=true
respackopts_button=true
toggle_incompatible=true
